#19 [Hook] add: Priseo field on selling price
Eoxia/priseo pull request #25
Opened 2024-06-05 10:07 UTC by evarisk-charles

2024-08-26 08:39 UTC, evarisk-micka requested changes
Ne fonctionne pas si l'option multiprice est activé (vérifier d'autres conditions au cas où)

2024-08-26 08:39 UTC, evarisk-micka commented on class/actions_priseo.class.php
> +            if (is_array($competitorPrices) && !empty($competitorPrices)) {
met un espace

2024-08-26 08:39 UTC, evarisk-micka commented on class/actions_priseo.class.php
> +                $out .= ucfirst($this->module) . ' (' . dol_print_date($lastCompetitorPrice->date_creation, 'day') . ')</td><td>' . $pictoPriseo . ' ';
saute une ligne à partir du nouveau <td>

2024-08-26 08:39 UTC, evarisk-micka commented on core/modules/modPriseo.class.php
>  				//   'data' => array(
retire les commentaires dans hooks[]

2024-08-26 08:44 UTC, nicolas-eoxia requested changes

2024-08-26 08:44 UTC, nicolas-eoxia commented on class/actions_priseo.class.php
> +/* Copyright (C) 2024 EOXIA <dev@eoxia.fr>
Cest pas ca ici check sur les autres projets

2024-08-26 08:44 UTC, nicolas-eoxia commented on class/actions_priseo.class.php
> +require_once DOL_DOCUMENT_ROOT . '/custom/saturne/lib/object.lib.php';
Je vois pas la raison du require ici

2024-08-26 08:44 UTC, nicolas-eoxia commented on class/actions_priseo.class.php
> +require_once 'competitorprice.class.php';
Même dans un require dans le même dossier il me semble qu'on couvre avec ./

Require global je suis pas fan ici

2024-08-26 08:44 UTC, nicolas-eoxia commented on class/actions_priseo.class.php
> +    public $resprints;
Pas à la norme dolibarr 20.0

2024-08-26 08:44 UTC, nicolas-eoxia commented on class/actions_priseo.class.php
> +     *  @param		DoliDB		$db      Database handler
Le spacing est bizarre

2024-08-26 08:44 UTC, nicolas-eoxia commented on class/actions_priseo.class.php
> +                $pictopath           = dol_buildpath('/custom/priseo/img/priseo_color.png', 1);
Premier / inutile

2024-08-26 08:44 UTC, nicolas-eoxia commented on class/actions_priseo.class.php
> +            $lastCompetitorPrices = $competitorPrice->fetchAll('DESC','rowid',1,0, ['customsql' => 't.status >= ' . $competitorPrice::STATUS_DRAFT . ' AND t.fk_product = ' . $object->id]);
Pourquoi un fetchall ici

2024-08-26 08:44 UTC, nicolas-eoxia commented on class/actions_priseo.class.php
> +            $competitorPrices     = $competitorPrice->fetchAll('DESC','amount_ht',0,0, ['customsql' => 't.status >= ' . $competitorPrice::STATUS_DRAFT . ' AND t.fk_product = ' . $object->id]);
Psr12

2024-08-26 08:44 UTC, nicolas-eoxia commented on core/modules/modPriseo.class.php
> +                'productpricecard'
Pourquoi c'est pas dans data check sur les autres modules

2024-08-28 08:27 UTC, evarisk-micka approved these changes

2024-08-28 11:35 UTC, nicolas-eoxia requested changes

2024-08-28 11:35 UTC, nicolas-eoxia commented on class/actions_priseo.class.php
> +            $lastCompetitorPrices = $competitorPrice->fetch('', '', ' ORDER BY t.rowid DESC');
Ça me paraît bizarre ça

2024-08-28 12:51 UTC, merged