#26 [Mod] add: url in extrafield
Eoxia/priseo pull request #27
Opened 2024-08-26 07:51 UTC by evarisk-charles

2024-08-26 08:44 UTC, evarisk-micka requested changes

2024-08-26 08:44 UTC, evarisk-micka commented on core/modules/modPriseo.class.php
> +                'pricesuppliercard'
retirer commentaire et pricesuppliercard

2024-08-26 08:44 UTC, evarisk-micka commented on core/modules/modPriseo.class.php
> +        global $langs;
pas utile

2024-08-26 08:44 UTC, evarisk-micka commented on core/modules/modPriseo.class.php
> +        $extraFields->update('product_url', 'URLCompetitor', 'varchar', '', 'product_fournisseur_price', 0, 0, $this->numero . 60, '', '', '', 1, 'URLCompetitorHelp', '', '', 0, 'priseo@priseo', "isM
.10 au lieu de .60

2024-08-26 08:49 UTC, nicolas-eoxia requested changes

2024-08-26 08:49 UTC, nicolas-eoxia commented on core/modules/modPriseo.class.php
> +        include_once DOL_DOCUMENT_ROOT . '/core/class/extrafields.class.php';
Faire require

2024-08-26 08:49 UTC, nicolas-eoxia commented on core/modules/modPriseo.class.php
> +        $extraFields->update('product_url', 'URLCompetitor', 'varchar', '', 'product_fournisseur_price', 0, 0, $this->numero . 60, '', '', '', 1, 'URLCompetitorHelp', '', '', 0, 'priseo@priseo', "isM
Il manque la taille du varchar

2024-08-26 08:49 UTC, nicolas-eoxia commented on langs/en_US/priseo.lang
> +URLCompetitorHelp                   = URL of the product page
La ça va pas et le choix de la clé pas en accord avec la trad et help inutile si c'est pour être égale à la trad

2024-08-28 08:20 UTC, evarisk-micka approved these changes

2024-08-28 13:12 UTC, merged